- name: Get variables
  hosts: all

  tasks:
    - name: Save all global variables for the complete workflow
      ansible.builtin.set_stats:
        data:
          sec_disp_server_list: "{{ my_sec_disp_srv_list }}"
          appl_server_list:     "{{ my_appl_server_list }}"
          eai_server_list:      "{{ my_eai_server_list }}"
        per_host: false
        aggregate: false

    - name: Save all global variables for the complete workflow
      ansible.builtin.set_fact:
        f_sec_disp_server_list: "{{ my_sec_disp_srv_list }}"
        f_appl_server_list:     "{{ my_appl_server_list }}"
        f_eai_server_list:      "{{ my_eai_server_list }}"
        cachable: true
