- hosts: all

  tasks:
    - name: Print my_sec_disp_srv_list
      debug:
        var: sec_disp_server_list

    - name: Print my_appl_server_list
      debug:
        var: appl_server_list

    - name: Print my_eai_server_list
      debug:
        var: eai_server_list

    - name: Print fact for my_sec_disp_srv_list
      debug:
        msg: "{{ ansible_facts['f_sec_disp_server_list'] }}"

    - name: Print fact my_appl_server_list
      debug:
        msg: "{{ ansible_facts['f_appl_server_list'] }}"

    - name: Print fact my_eai_server_list
      debug:
        msg: "{{ ansible_facts['f_eai_server_list'] }}"
